---
- name: Create docker_folder directory
  file: path={{ docker_folder }}/build state=directory
  
- name: Copy Dockerfile
  copy:
    src: docker/Dockerfile
    dest: "{{ docker_folder }}/build/Dockerfile"
    
- template:
    src: docker-compose.yml.j2
    dest: "{{ docker_folder }}/docker-compose.yml"
    
- name: Rebuilds docker container
  command: /usr/bin/docker-compose -f {{ docker_folder }}/docker-compose.yml -p apache build
  
- template:
    src: etc/systemd/system/apache_docker.service.j2
    dest: /etc/systemd/system/apache_docker.service
    
- name: Restart httpd service
  systemd:
    state: restarted
    daemon_reload: yes
    name: apache_docker 